import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/provider/ReduxProvider";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css" />
      </Head>
      <ReduxProvider>
        <body className={inter.className} suppressHydrationWarning={true} >{children}</body>
      </ReduxProvider>
    </html>
  );
}
