import "./globals.css";
import { Poppins } from "next/font/google";
import { ReduxProvider } from "@/provider/ReduxProvider";
import { ThemeProvider } from "@/context/ThemeContext";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Get My Location App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <ReduxProvider>
          <body className={poppins.className} suppressHydrationWarning={true}>
            {children}
          </body>
        </ReduxProvider>
      </ThemeProvider>
    </html>
  );
}
